#pragma once
#include <cstdint>

// /////////////////////////////////////////////////////////////
// Module: client
// Created using source2gen - github.com/neverlosecc/source2gen
// /////////////////////////////////////////////////////////////

namespace source2sdk::client
{
    // Enumerator count: 87
    // Alignment: 4
    // Size: 0x4
    enum class Class_T : std::uint32_t
    {
        CLASS_NONE = 0x0,
        CLASS_PLAYER = 0x1,
        CLASS_PLAYER_ALLY = 0x2,
        CLASS_MODIFIER_THINKER = 0x3,
        CLASS_TROOPER = 0x4,
        CLASS_TROOPER_BOSS = 0x5,
        CLASS_TROOPER_NEUTRAL = 0x6,
        CLASS_SUPER_NEUTRAL = 0x7,
        CLASS_SUPER_NEUTRAL_HEROTEST = 0x8,
        CLASS_SIEGE = 0x9,
        CLASS_GUN = 0xa,
        CLASS_CAP_POINT = 0xb,
        CLASS_ITEM_SHOP = 0xc,
        CLASS_ABILITY_SHOP = 0xd,
        CLASS_MINI_MAP_MARKER = 0xe,
        CLASS_ABILITY = 0xf,
        CLASS_ABILITY_PROJECTILE = 0x10,
        CLASS_CRATE = 0x11,
        CLASS_CRATE_SPAWN = 0x12,
        CLASS_PICKUP_SPAWN = 0x13,
        CLASS_VEHICLE = 0x14,
        CLASS_FLARE = 0x15,
        CLASS_SPAWNED_DRONE = 0x16,
        CLASS_ROLLERMINE = 0x17,
        CLASS_PERCHED_PREDATOR_PROJECTILE = 0x18,
        CLASS_PARACHUTE = 0x19,
        CLASS_SENTRY = 0x1a,
        CLASS_BASE_SENTRY = 0x1b,
        CLASS_DISPENSER = 0x1c,
        CLASS_SPY_DRONE = 0x1d,
        CLASS_GOLD_ORB = 0x1e,
        CLASS_LANE_NODE = 0x1f,
        CLASS_WARD = 0x20,
        CLASS_ZIP_LINE_NODE = 0x21,
        CLASS_DESTROYABLE_BUILDING = 0x22,
        CLASS_BOSS_TIER_2 = 0x23,
        CLASS_BOSS_BARRACKS = 0x24,
        CLASS_BOSS_TIER_3 = 0x25,
        CLASS_BOSS_TIER_3_DRONE = 0x26,
        CLASS_ANNOUNCER = 0x27,
        CLASS_WEAK_NEUTRAL_CAMP = 0x28,
        CLASS_MEDIUM_NEUTRAL_CAMP = 0x29,
        CLASS_STRONG_NEUTRAL_CAMP = 0x2a,
        CLASS_VAULT_NEUTRAL_CAMP = 0x2b,
        CLASS_SUPER_NEUTRAL_CAMP = 0x2c,
        CLASS_SUPER_NEUTRAL_CAMP_HEROTEST = 0x2d,
        CLASS_LADDER = 0x2e,
        CLASS_EXPLOSIVE_BARREL = 0x2f,
        CLASS_PAYLOAD = 0x30,
        CLASS_BULLET_TIME_WARP = 0x31,
        CLASS_BREAKABLE_PROP_PICKUP = 0x32,
        CLASS_ITEM_PICKUP = 0x33,
        CLASS_GOLDEN_IDOL_PICKUP = 0x34,
        CLASS_HERO_CLONE = 0x35,
        CLASS_TRIGGER_HURT = 0x36,
        CLASS_DRONE_DISPENSER = 0x37,
        CLASS_HERO_MINION = 0x38,
        CLASS_PING_MARKER = 0x39,
        CLASS_PING_LOCATION_TRIGGER = 0x3a,
        CLASS_TESLA_COIL = 0x3b,
        CLASS_FARADAY_CAGE = 0x3c,
        CLASS_DIRECTOR_CAMERA = 0x3d,
        CLASS_BREAKABLE_PROP = 0x3e,
        CLASS_TRIGGER_IDOL_RETURN = 0x3f,
        CLASS_TRIGGER_SHOP_TUNNEL = 0x40,
        CLASS_TRIGGER_TELEPORT = 0x41,
        CLASS_TRIGGER_MODIFIER = 0x42,
        CLASS_TRIGGER_OBSCURED_VOLUME = 0x43,
        CLASS_TRIGGER_ZIPLINE_CAPTURE = 0x44,
        CLASS_TRIGGER_CATAPULT = 0x45,
        CLASS_TRIGGER_CLIMB_ROPE = 0x46,
        CLASS_BALLISTA_BOMB = 0x47,
        CLASS_BALLISTA_MINE = 0x48,
        CLASS_TOMBSTONE = 0x49,
        CLASS_ICEPATH_SHARD = 0x4a,
        CLASS_TRICKSHOT_TARGET = 0x4b,
        CLASS_GUIDED_ARROW = 0x4c,
        CLASS_PING_LOCATION = 0x4d,
        CLASS_DUSTSTORM_PROJECTILE = 0x4e,
        CLASS_CYCLONE_PROJECTILE = 0x4f,
        CLASS_FIELD_SENTRY = 0x50,
        CLASS_RIPTIDE_PROJECTILE = 0x51,
        CLASS_ZAP_TRIGGER = 0x52,
        CLASS_VISCOUS_CUBE = 0x53,
        CLASS_FISSURE_WALL_SEGMENT = 0x54,
        CLASS_NANO_STATUE = 0x55,
        NUM_CLASSIFY_CLASSES = 0x56,
    };
};
